baseURL: https://koudijs.dev/
languageCode: en-us
title: koudijs.dev
pagination:
  pagerSize: 5

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: koudijs.dev
  description: "Consultant, trainer, and speaker on software delivery, platform engineering, Kubernetes, GitOps, and AI in engineering."
  keywords: [Consulting, Training, Platform Engineering, Kubernetes, GitOps, Software Delivery, AI]
  author: Simon Koudijs
  gitRepo: https://github.com/koudijs-dev/public-website
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # search https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 800
    threshold: 0.6
    minMatchCharLength: 3
    keys: ["title", "permalink", "summary", "content"]

  profileMode:
    enabled: true
    subtitle: "Consultant, trainer, and speaker on software delivery, platform engineering, GitOps and of course AI."
    imageUrl: "images/simon-2026.webp"
    imageTitle: "Simon Koudijs"
    imageWidth: 220
    imageHeight: 220
    buttons:
    - name: ICT
      url: "https://www.ict.eu"

outputs:
  home:
  - HTML
  - RSS
  - JSON

menu:
  main:
    - name: training
      url: training
      weight: 10
    - name: speaking
      url: speaking
      weight: 10
    - name: about
      url: about
      weight: 20
    - name: search
      url: search/
      weight: 10
    - identifier: tags
      name: tags
      url: tags
      weight: 20

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
   tag: tags
   series: series
