name: Publish stuff yeahj

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # manual run

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v7

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.163.3'
          extended: true

      - name: Build
        run: hugo --minify
        env:
          HUGO_PARAMS_gitsha: ${{ github.sha }}   # version footer (links to the commit)

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
